modLoader = "javafml"
loaderVersion = "[10,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "altlook"
version = "${version}"
displayName = "altlook"
authors = "Cataratas"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.altlook]]
modId = "neoforge"
type = "required"
versionRange = "[21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.altlook]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.altlook]]
modId = "architectury"
type = "required"
versionRange = "[18.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "altlook.mixins.json"
