modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "altlook"
version = "${version}"
displayName = "AltLook"
authors = "Cataratas"
description = '''

'''
#logoFile = ""

[[dependencies.altlook]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.altlook]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.altlook]]
modId = "architectury"
type = "required"
versionRange = "[18.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "altlook.mixins.json"
